### ISSUE TITLE
record: non-generative record types

### ISSUE THREAD

**Issue by mikesperber** [active-group/active-clojure#10]

**Comment by mikesperber** [comment]
Simple case:
<pre>
(define-record-type Container
  {:nongenerative true}
  ...)
</pre>

Advanced case:
<pre>
(define-record-type Container
 {:nongenerative "00112233-4455-6677-8899-aabbccddeeff"}
 ...)
</pre>

Also possible uuid: keyword

In the simple case, a uuid is generated at macro-expansion time.

See also http://www.r6rs.org/corrected/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_sec_6.3

**Comment by kaaninho** [comment]
Added with a9f9debbde62597cb50c6412230c9da6e61f05b6
