### ISSUE TITLE
Compiler warning in record.cljc with clojurescript

### ISSUE THREAD

**Issue by dfrese** [active-group/active-clojure#19]
For example, when running the tests:
```
WARNING: Wrong number of args (3) passed to active.clojure.record-test/make-pu at line 53 .../active-clojure/test/active/clojure/record_test.cljc
```

Unsure where that comes from. Tests are successding anyway.

**Comment by kaaninho** [comment]
Bug, that only occurs, when 
- `constructor-call`-form does not contain all field names and
- a `lens` `shove` operation on such a record is performed.

Fixed in fd7562894e8af23d7dacbd0fc813d7589bb2c364
