### ISSUE TITLE
records: Metadata should be passed/inherited to generated symbols

### ISSUE THREAD

**Issue by dfrese** [active-group/active-clojure#22]
For example, when specifying that a record definition is private:

```
(define-record-type ^:private X ...)
```

The generated `defrecord`, the therefore `->X` and `map->X` and so on, are not marked private (and there is no way to do it, methinks). This has especially a large impact on generated documentation via codox for example (which automatically includes all public symbols).

Also, it would be convenient if the metadata on the Type symbol would be the default for/merged into the generated symbols of the constructor and accessors.

**Comment by kaaninho** [comment]
Added with ef47814df39905874e2cb658e2dd278ff6eef487
