### ISSUE TITLE
records: Cljs records with at least one field fail on `keys` function

### ISSUE THREAD

**Issue by smoes** [active-group/active-clojure#23]
The error can be reproduced by defining a record with at least one field in clojurescript as follows:

```
(define-record-type foo (make-foo a b) foo? [a foo-a b foo-b])
```
... and calling `keys` on it:

```
(keys (make-foo 1 2)) => #object[TypeError TypeError: undefined is not a constructor (evaluating 'me.cljs$core$IMapEntry$_key$arity$1(null)')]
``` 

Since these records needs to be downward compatible, the `keys` function should work properly.

**Comment by kaaninho** [comment]
Fixed with e778dad1db691bad3cd68f230ce305b59cb3555e .
Bug occurred due to ClojureScript version update. Inlined CLJS code was too old.
