### ISSUE TITLE
`default` as a field name doesn't work in ClojureScript

### ISSUE THREAD

**Issue by kaaninho** [active-group/active-clojure#26]
For example
```clojure
(define-record-type MyDefaultFieldRecord
  (make-mdfr a default)
  mdfr?
  [a mdfr-a
   default mdfr-default])

(mdfr-default (make-mdfr 1 1)))))
```
returns `nil` instead of `1`.

**Comment by kaaninho** [comment]
This is not a bug of `define-record-type`. `default` is a special keyword in Javascript, therefore clashing in some way.

This will most likely happen with other keywords too.

**Comment by dfrese** [comment]
```clojure
(def default 42)
(/ 1 default)
```

works, though.

**Comment by dfrese** [comment]
Looked at it again. At least this is not the case for `rtd-record?`s - they "work".

And it stems from Clojurescript's `defrecord`, which has the same problem.
So we can see it as a bug in Clojurescript, which is probably already known as: https://clojure.atlassian.net/browse/CLJS-3201
