### ISSUE TITLE
Constructor arguments not being assigned to an accessor should cause syntax errors

### ISSUE THREAD

**Issue by smoes** [active-group/active-clojure#27]
A minimal working example, that should fail, but doesn't, is:
```
(define-record-type A
  {:java-class? false}
  (make-a foo)
  a?
  [])
```

Since `foo` is part of the constructor but not assigned to an accessor in the field vector, this definition is invalid.

**Comment by kaaninho** [comment]
Fixed with 79241994c30574a51c6ad74a53ad166f9b210446 .
