### ISSUE TITLE
`constructor` as a field name in clojurescript records messes up

### ISSUE THREAD

**Issue by smoes** [active-group/active-clojure#30]
With a record defined as follows:
```
(rec/define-record-type CallbackMessage
  (make-callback-message handler constructor) callback-message?
  [handler callback-message-handler
   constructor callback-message-constructor])
```
... the accessor call `(callback-message-constructor callback-message-inst)` returns `CallbackMessage`, that is, the record type itself. For rtd-records, it works as intended. I'm not sure if this fails in clojure aswell.

**Comment by smoes** [comment]
```
(rec/define-record-type CallbackMessage
  (make-callback-message handler constr) callback-message?
  [handler callback-message-handler
   constr callback-message-constructor])
```

This works as intended!

**Comment by kaaninho** [comment]
It's a bug in ClojureScript, see issue #30

Closed therefore.
