### ISSUE TITLE
Equality checks differ between regular and rtd-records.

### ISSUE THREAD

**Issue by neshtea** [active-group/active-clojure#41]
# Observation

The result of equality-checks seem to differ between "regular" and `rtd`-records on Clojure.

# Expectation

I would expect that comparing values constructed with a "regular" record constructor yields the same results as comparing values constructed with a `rtd`-record constructor. It seems that this is not the case:

```clojure
(define-record-type Foo
  make-foo foo?
  [i foo-id])

(define-record-type Bar {:rtd-record? true}
  make-bar bar?
  [i bar-i])

(= (make-foo 42)
   (make-foo (int 42)))
;; => true

(= (make-bar 42)
   (make-bar (int 42)))
; ; => false
```
Equality checks with `rtd`-records seem to care about the actual type of a value (here it's `java.lang.Long` vs `java.lang.Integer`).  Both results can be considered correct, but I think something has to be done. I would propose to either

1. disclose this difference to the user and mention one such example in the readme/documentation, or
2. eliminate the difference (if possible)

Thoughts?

**Comment by kaaninho** [comment]
We went with option 2. With commit https://github.com/active-group/active-clojure/commit/1e11b7ff39a8cea22e2b0d808ab772e213b69f8b this 
```clojure
(define-record-type Bar {:rtd-record? true}
  make-bar bar?
  [i bar-i])

(= (make-bar 42)
   (make-bar (int 42)))
```
returns `true`.
