### ISSUE TITLE
record: allow overriding equality

### ISSUE THREAD

**Issue by mikesperber** [active-group/active-clojure#8]

**Comment by mikesperber** [comment]
This means that providing an implementation for `clojure.lang.IHashEq` (on the Clojure side) should cause the internal implementation to not happen.

**Comment by kaaninho** [comment]
It is now possible to provide an implementation of `clojure.lang.IHashEq`.
This overrides (among others) the `equals` function.
`=` on `active-records` uses `equiv` of `clojure.lang.IPersistentMap`, so by now, you can only use your equality implementation via `.equals` and not `=`.
